databases:
  - name: Lucky SecTest Primary
    databaseName: lucky_sectest
    user: lucky_sectest
    ipAllowList: []

services:
  - type: web
    name: Lucky SecTest
    env: docker
    dockerfilePath: "./dockerfiles/webserver.Dockerfile"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Lucky SecTest Primary
          property: connectionString
      - key: LUCKY_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: APP_DOMAIN
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: SEND_GRID_KEY
        sync: false
